from pathlib import Path

root = Path(__file__).parent / "docs"
docs = {
    "README.md": """# Documentation

This documentation describes the current Stream Runtime repository, not an aspirational implementation. Read [Getting Started](getting-started/installation.md) first, then [Architecture Overview](architecture/overview.md) and [Development Setup](development/development-setup.md).

## Documentation status

**Implemented:** CPU safetensors range streaming, managed memory accounting, generic sequential linear execution, tiled linear operator, local FastAPI server, model registry, queued single-request serving, JSON/SSE endpoints, local API keys, tracing, and test coverage.

**Experimental:** generic graph analysis, embedding/residual executor hooks, async worker-thread storage facade, conservative prefetch admission, token generator interface, local deterministic chat adapter.

**Planned:** real transformer/tokenizer adapters, disk-backed activations, CUDA/VRAM execution, cache integration in serving, true incremental language-model decoding, and broader OpenAI features.
""",
    "getting-started/installation.md": """# Installation

Use Python 3.9 or newer. From the repository root:

```bash
python -m venv .venv
. .venv/bin/activate
python -m pip install -e .
```

The project uses PyTorch, NumPy, safetensors, FastAPI, Uvicorn, and pytest. Runtime code does not install packages or download models. Install dependencies and copy model files while online, then inference can run offline.
""",
    "getting-started/quickstart.md": """# Quickstart

```bash
python examples/create_test_model.py --output /tmp/model.safetensors
python -m stream_runtime prepare /tmp/model.safetensors --output /tmp/prepared
python -m stream_runtime inspect /tmp/model.safetensors
python -m stream_runtime plan /tmp/prepared --ram-budget 1M
python -m stream_runtime run /tmp/prepared --ram-budget 1M --trace
```

Start a server with `python -m stream_runtime serve --model /tmp/prepared --ram-budget 1M --api-key local`.
""",
    "getting-started/configuration.md": """# Configuration

The main configuration is the managed `--ram-budget`, accepted as raw bytes or binary K/KB/M/MB/G/GB. `--cache-size` is exposed by the server but cache admission is not yet integrated into the serving engine (**planned**). `--vram-budget` is not implemented. `--api-key`, `--no-auth`, `--request-timeout`, `--host`, and `--port` configure the local server.
""",
    "getting-started/first-model.md": """# First Model

The supported proof-of-concept model is generated by `examples/create_test_model.py`. It contains two sequential linear nodes in safetensors format. Preparation creates a manifest without loading all weights. The server's chat adapter converts prompt text to a deterministic vector because a real tokenizer and language-model head are **not implemented** yet.
""",
    "getting-started/troubleshooting.md": """# Troubleshooting

**`prepared model requires manifest.json and model.path`:** run `prepare` first and point `serve` at the prepared directory. **`local model not found`:** verify the directory is local and contains both files. **`MemoryBudgetExceeded`:** increase the managed budget or use an operator with a supported tiling strategy. **401:** use `Authorization: Bearer <configured key>` or explicitly pass `--no-auth`. **No tokenizer:** this repository currently uses the deterministic demo encoder; real tokenizer support is planned.
""",
    "user-guide/model-management.md": """# Model Management

A prepared model directory contains `manifest.json`, `metadata.json`, and `model.path`. The safetensors file remains at its original location. The current registry discovers the explicitly served prepared directory; multi-model discovery is designed but not a full model manager.
""",
    "user-guide/model-preparation.md": """# Model Preparation

`prepare` reads safetensors metadata and uses the generic adapter to group matching `.weight` and `.bias` names into logical nodes. It does not call `AutoModel.from_pretrained` or `load_file`. The generic adapter is best effort and does not represent general Hugging Face support.
""",
    "user-guide/memory-budgets.md": """# Memory Budgets

The budget limits runtime-managed reservations, not total process RSS. Managed categories include weights, activations, temporary memory, cache, and the future prefetch category. Before each reservation, current managed bytes plus requested bytes must fit. Python, PyTorch allocators, shared libraries, OS page cache, and GPU allocations are outside this guarantee.
""",
    "user-guide/local-server.md": """# Local Server

```bash
python -m stream_runtime serve --model ./prepared_model --host 127.0.0.1 --port 8000 --ram-budget 512M --api-key local
```

The server is local-only by default. It uses FastAPI/Uvicorn, runs blocking inference in a worker thread, and serializes active generations through an asyncio lock. `--trace` is currently available on the CLI `run` path; server logging is normal Uvicorn/Python logging (**server trace flag: planned**).
""",
    "user-guide/openai-api.md": """# OpenAI-Compatible API

Supported endpoints are `GET /health`, `GET /v1/models`, `GET /v1/status`, `POST /v1/chat/completions`, and `POST /v1/completions`. Local Bearer authentication is enabled by default. Compatibility means the implemented subset only; tool calls, embeddings, image/audio APIs, logprobs, and full parameter parity are **planned/not supported**.
""",
    "user-guide/streaming.md": """# Streaming

Set `"stream": true` on chat completions. The response is `text/event-stream` with OpenAI-style `data: ...` chunks and a final `data: [DONE]`. The current demo splits its deterministic response into ordered word chunks; incremental model token decoding is **planned**.
""",
    "user-guide/offline-mode.md": """# Offline Mode

Install packages and place prepared model files locally before disconnecting. The serving code has no Hugging Face, OpenAI, Anthropic, Google, telemetry, model-download, DNS, or remote-inference path. Verify with `curl` against localhost and inspect the source if operating in a restricted environment.
""",
    "user-guide/cli.md": """# CLI

Commands: `inspect MODEL`, `prepare MODEL_DIR --output DIR`, `plan PREPARED --ram-budget SIZE`, `run PREPARED --ram-budget SIZE [--trace]`, `serve --model DIR --ram-budget SIZE`, `models`, `status`, and `test`. `models`/`status` query the configured local HTTP endpoint and are not model-management commands.
""",
    "architecture/overview.md": """# Architecture Overview

```mermaid
flowchart TD
 C[HTTP client]-->S[FastAPI local server]-->Q[Request manager]
 Q-->E[Generation / execution]
 E-->P[Memory planner]
 E-->G[Model graph]
 G-->X[Node executor]
 X-->T[TensorStore]
 T-->F[SafeTensorStream]
 F-->D[SSD/HDD]
 E-->A[Async worker-thread I/O]
```

The HTTP layer does not parse safetensors offsets. Storage does not know HTTP. The scheduler abstractions are independent of FastAPI.
""",
    "architecture/design-principles.md": """# Design Principles

Correctness precedes performance. Model size may exceed RAM. Logical nodes are architecture boundaries; physical tiles are internal. The runtime preserves source dtype and weights by default. Unsupported unavoidable working sets fail clearly instead of silently changing the model.
""",
    "architecture/execution-model.md": """# Execution Model

Preparation creates metadata and a graph. At inference, dependencies are checked in order, the loader identifies current-node tensors, the executor streams required ranges, computes, and releases node resources. The current engine operates synchronously per node; async storage and queue/server integration are separate layers.
""",
    "architecture/model-graph.md": """# Model Graph

`ModelGraph` serializes format version, architecture, model type, execution order, nodes, and tensor metadata. `Node` contains id, name, type, inputs, outputs, weights, estimated memory, and dependencies. The generic adapter groups names by module prefix rather than by file size.
""",
    "architecture/architecture-analysis.md": """# Architecture Analysis

`ArchitectureAdapter` is the extension point. `ArchitectureAdapter.analyze(reader)` returns nodes and tensor metadata. The current generic implementation is appropriate only for simple sequential weight/bias naming. A production Hugging Face adapter must inspect local config/module hierarchy and add confidence and limitations.
""",
    "architecture/node-system.md": """# Node System

A node is a complete logical computational unit such as a linear layer. `NodeLoader` selects only its declared weights. `NodeExecutor` maps the node type to an operator. Dependencies are authoritative and the engine rejects unsatisfied dependencies.
""",
    "architecture/tensor-storage.md": """# Tensor Storage

`TensorStore` abstracts storage from operators. `SafeTensorStream` is the current backend. Future backends may implement a common range-read interface for sharded, mmap, compressed, or remote storage; remote storage is not used by the current offline server.
""",
    "architecture/safetensors.md": """# Safetensors

The reader reads the 8-byte little-endian header length, then only the JSON header. Each descriptor records dtype, shape, and data offsets. `tensor.read(offset,length)` uses a seek/read range; `iter_chunks` yields ranges. `read_log`, `bytes_read`, and `reads` support streaming tests. No complete tensor or file is loaded by metadata inspection.
""",
    "architecture/memory-management.md": """# Memory Management

`MemoryManager.reserve` checks the budget and returns a context-compatible `Reservation`; `release` decrements category counters. `MemoryStats` tracks current, peak, weights, activations, cache, and temporary bytes. This is logical managed memory, not RSS. The current demo's PyTorch output tensor is not fully integrated into category reservations; improving this accounting is planned.
""",
    "architecture/memory-planner.md": """# Memory Planner

`MemoryPlanner` estimates each node from declared weight bytes plus a safety reserve. Nodes fit directly when the estimate is within the budget; otherwise linear execution chooses an output-row tile. It is deterministic and conservative, but activation-aware planning is still experimental.
""",
    "architecture/tiling.md": """# Tiling

`StreamingLinear` computes `X @ W.T` one output-row tile at a time. Tile rows are derived from available planner bytes and weight-row size. The logical node remains a single node. Temporary conversion and output accounting are areas for future tightening. Tiled accumulation may differ slightly because floating-point order can change.
""",
    "architecture/scheduler.md": """# Scheduler

`SyncScheduler` is the simple scheduler. `AsyncScheduler` provides a conservative prefetch admission hook and does not yet retain prefetched tensor data. The HTTP request manager uses an asyncio lock to allow one active generation and queue others. Batching and continuous scheduling are planned.
""",
    "architecture/async-execution.md": """# Async Execution

`AsyncTensorStore` runs blocking reads in a `ThreadPoolExecutor`, avoiding the false pattern of calling blocking I/O directly in an async function. The server uses `asyncio.to_thread` for CPU inference. Node dependency execution remains serialized. Cancellation and prefetch cancellation are limited by Python worker semantics and are future work.
""",
    "architecture/token-generation.md": """# Token Generation

`TokenGenerator.generate` is an async ordered interface. The current server returns a deterministic demo response rather than incremental language-model decoding. External token order is serialized by the generator/API design. KV cache and true autoregressive decoding are planned.
""",
    "architecture/request-lifecycle.md": """# Request Lifecycle

An HTTP request is authenticated, parsed, assigned an id, queued behind the request manager lock, executed in a worker thread, and converted to JSON or SSE. The model transitions from UNLOADED to INITIALIZING to READY and RUNNING during first/useful inference. Timeout responses are supported; disconnect-aware cancellation and explicit model unload are planned.
""",
    "architecture/api-server.md": """# API Server

`create_app` constructs the FastAPI application without contacting external services. `run_server` starts Uvicorn. Errors are returned as `{error:{message,type,code}}`; detailed stack traces go to server logs. Default binding is `127.0.0.1`.
""",
    "architecture/caching.md": """# Caching

`TensorChunkCache` is a bounded LRU implementation and its byte count can be integrated into managed memory. The server's `--cache-size` option is accepted, but active serving does not yet populate this cache. This is **experimental/planned**.
""",
    "architecture/cpu-execution.md": """# CPU Execution

CPU is the only implemented device. Operators use PyTorch tensors after controlled range reads. CUDA/VRAM is not required and no fake GPU support is exposed.
""",
    "architecture/gpu-execution.md": """# GPU Execution

CUDA, VRAM budgeting, CPU-to-GPU streaming, and `CUDADevice` are **not implemented**. Do not infer GPU memory guarantees from `--ram-budget`.
""",
    "architecture/numerical-fidelity.md": """# Numerical Fidelity

The goal is original weights, dtype, architecture, and operator semantics. Bitwise identity is not promised. Tiling, BLAS kernels, CPU/GPU differences, and accumulation order can change low-order bits. Tests use `torch.allclose`/`torch.testing.assert_close` with documented tolerances where appropriate.
""",
    "development/development-setup.md": """# Development Setup

Create a virtual environment, install with `pip install -e .`, and run `pytest -q`. The project has no external service requirement. Generate a small model with `examples/create_test_model.py` for manual checks.
""",
    "development/repository-layout.md": """# Repository Layout

`stream_runtime/storage` handles range reads and cache; `memory` handles reservations; `graph` stores manifests; `architecture` analyzes models; `operators` computes; `planner` chooses strategies; `activation` stores activations; `runtime` loads/executes/generates; `server_core.py` owns local model/request state; `server.py` owns HTTP adaptation; `examples` contains runnable scripts; `tests` contains unit/integration tests.
""",
    "development/coding-standards.md": """# Coding Standards

Prefer small modules, dataclasses, type hints for new public APIs, docstrings, explicit exceptions, and deterministic tests. Keep HTTP concerns out of storage and keep operators dependent on `TensorStore`, not file paths. Document implemented versus planned behavior.
""",
    "development/testing.md": """# Testing

Run `pytest -q`. Tests cover range reads, metadata, cache bounds, memory failures, async reads, tiled inference, and the ASGI server. The server test uses `httpx.ASGITransport`, so it does not require a network socket. Add a regression test before changing a memory or streaming invariant.
""",
    "development/debugging.md": """# Debugging

Use `python -m stream_runtime run ... --trace` to observe node reads, execution, and release. Inspect `SafeTensorStream.read_log`, `bytes_read`, `reads`, and `MemoryManager.stats`. For HTTP issues, run Uvicorn in the foreground and inspect structured client errors plus server logs.
""",
    "development/profiling.md": """# Profiling

Performance profiling is not the first milestone. Use Python profiling around `StreamingEngine.run`, record `bytes_read` and read count, and separately measure PyTorch compute. Do not interpret OS page-cache behavior as controlled managed memory.
""",
    "development/benchmarking.md": """# Benchmarking

Record model size, budget, node count, strategy, wall time, read count, bytes read, peak managed memory, and output tolerance. Compare reference and streaming outputs using identical seeds and inputs. Benchmarking suites and SSD/NVMe comparisons are future work.
""",
    "development/adding-operators.md": """# Adding Operators

Add an operator module with a narrow interface: input activation, declared node weights, manager/store access, selected strategy, output, and explicit release. Provide a direct reference implementation and a streaming/tiled implementation. Preserve dtype unless the operator explicitly documents a safe conversion. Include minimum-working-set failure behavior, range-read assertions, and `torch.testing.assert_close` tests. Never open safetensors files directly from an operator; use `TensorStore`.
""",
    "development/adding-model-architectures.md": """# Adding Model Architectures

1. Identify local config and module hierarchy. 2. Define complete logical boundaries. 3. Map tensor names to nodes. 4. Implement an `ArchitectureAdapter`. 5. Map operators. 6. Add local tokenizer/chat-template handling. 7. Add deterministic reference-vs-streaming tests. 8. Document unsupported cases and confidence. 9. Register the adapter. The current generic adapter is the concrete baseline, but it is not a full transformer architecture.
""",
    "development/adding-storage-backends.md": """# Adding Storage Backends

Implement the range-read contract used by `TensorStore` and preserve metadata descriptors. Keep byte reads instrumentable. Add tests proving unrelated ranges are not read. A future sharded or mmap backend must not change the engine's memory semantics.
""",
    "development/adding-schedulers.md": """# Adding Schedulers

Schedulers must honor graph dependencies, memory admission, ordered outputs, backpressure, and cleanup. Keep scheduler code independent of FastAPI. Start with a deterministic synchronous test, then add async timing tests. Prefetch must be admitted only when its buffers are accounted for.
""",
    "api/README.md": """# API Reference

See [Server API](server-api.md), [Python API](python-api.md), and [Configuration API](configuration-api.md). The HTTP API is a tested local subset of OpenAI-compatible behavior.
""",
    "api/python-api.md": """# Python API

Core entry points include `SafeTensorStream`, `TensorStore`, `MemoryManager`, `MemoryPlanner`, `ModelGraph`, `StreamingEngine`, `NodeLoader`, `NodeExecutor`, `AsyncTensorStore`, and `TokenGenerator`. Their current behavior is defined by source and tests; import paths are under `stream_runtime`.
""",
    "api/server-api.md": """# Server API

`create_app(model_dir, ram_budget, model_id=None, api_key='local', no_auth=False, request_timeout=None, cache_size=0)` returns a FastAPI application. `run_server` launches Uvicorn. The server endpoints are documented in `docs/user-guide/openai-api.md`.
""",
    "api/configuration-api.md": """# Configuration API

CLI size parsing is implemented by `stream_runtime.cli.parse_bytes`. It accepts raw bytes and binary K/KB/M/MB/G/GB. Server constructor options map directly to local model directory, budget, key, timeout, and cache-size.
""",
    "reference/configuration-reference.md": """# Configuration Reference

| Option | Status | Meaning |
|---|---|---|
| `--ram-budget` | Implemented | Managed runtime memory ceiling |
| `--cache-size` | Experimental | Accepted server option; cache population planned |
| `--vram-budget` | Not implemented | Future GPU budget |
| `--api-key` | Implemented | Local Bearer key |
| `--no-auth` | Implemented | Disable local auth explicitly |
| `--request-timeout` | Implemented | Server request timeout seconds |
""",
    "reference/cli-reference.md": """# CLI Reference

`inspect`, `prepare`, `plan`, `run`, `test`, `serve`, `models`, and `status` are implemented. Run `python -m stream_runtime COMMAND --help` for parser details.
""",
    "reference/environment-variables.md": """# Environment Variables

The runtime does not define model-download, cloud, telemetry, or API-key environment variables. Configuration is explicit CLI/application arguments. No external service credentials are required.
""",
    "reference/error-codes.md": """# Error Codes

HTTP errors use `INVALID_API_KEY`, `REQUEST_TIMEOUT`, and `INFERENCE_ERROR` where applicable. Core failures include `MemoryBudgetExceeded`, malformed safetensors metadata errors, missing prepared-model files, and unsupported operator/model limitations.
""",
    "reference/glossary.md": """# Glossary

**Managed memory:** explicitly reserved runtime buffers. **Logical node:** architecture-level computational unit. **Tile:** internal operator subdivision. **TensorStore:** storage abstraction. **Prefetch:** optional future/current admission of upcoming data. **SSE:** Server-Sent Events streaming format.
""",
    "design/adr/0001-streaming-boundaries.md": """# ADR 0001: Logical Nodes, Physical Tiles

**Decision:** preserve architecture-aware logical nodes and use internal tiling for oversized operators. **Reason:** arbitrary byte boundaries do not preserve computation semantics. **Consequence:** every new architecture adapter must define valid node boundaries; every tiled operator must prove its working set and output fidelity.
""",
}
for name, text in docs.items():
    p = root / name
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(text)
print(f"wrote {len(docs)} documentation files")
